### ISSUE TITLE
Prototype callouts

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions-gif#31]
Try out different things - arrows, lines, just the text, etc - in powerpoint. Do we point to specific regions by circling the area or pointing to the gages, or just show the text in the appropriate region.

See static figure for water use 15 (ultimately completed in illustrator). Maybe take "hand drawn" image and convert to data points, e.g. draw shape to highlight a region and convert into points that we could plot. Ask Marty if he has experience/ideas.

**Comment by jread-usgs** [comment]
![image](https://user-images.githubusercontent.com/2349007/48201903-13ca7600-e329-11e8-9202-c8ee0cce5916.png)


These are simple examples, but show some of the callout needs we'll have in a given year. 

I think the animation would be best served by having a number of different ways we can do callouts, similar to water use. That includes overlay boxes, arrows, custom text formatting, and polygon outlines of various types to show extent. *But*, we're limited by complexity challenges, so I think we should proceed with simpler technical implementations first and add on top as needed later. I know the task here isn't about implementation, but I think that is where I can help out most at least in the brainstorming phase. I tried to limit solutions to practical things that I think we can code up relatively easily. 

I think a yaml pattern like this may be helpful for us:

```yaml
callouts:
   - 
     dates: ["2018-06-01", "2018-06-11"]
     text: 
          label: ["Flooding in the northeast", "driven by x…"]
          x_loc: 0.88 #this is in percentage space, relative to the plotting device
          y_loc: 0.65
          pos: 3
   -      
     dates: ["2018-05-21", "2018-07-01"]
     text: 
          label: ["Drought conditions", "established in Colorado"]
          x_loc: 0.47
          y_loc: 0.45
          pos: 3
     text_box: 
          bg: "#A9A9A9CC"
```

I'd suggest we skip arrows for now, or only support simple arrows w/o curves. Although I'm tempted to specify a pattern for circles or ellipses (or merged buffered points like we have in Arkansas for WU), I think it might not be necessary, so we should probably skip it for now. If, for example, we end up with only 5 callouts for the entire year, I would guess we'd want to tweak those to look as sharp as possible. That means either creating some kind of external polygon to read in and plot (doesn't sound fun), or having callout-specific image files created manually (e.g., same resolution and size as the frames) that _only_ have the overlay polygons and/or custom arrows. I'd prefer this solution as it seems more practical. These images could be PNGs w/ transparency that can be read in and plotted on top similar to how the watermark is handled (but easier, since the watermark image isn't the right size and doesn't have proper transparency, so we need to mess with it). Not sure if there are other ideas that others have in mind for this too - additional input welcome. 

So, something like this *in the future if needed*:
```yaml
callouts:
   - 
     dates: ["2018-06-01", "2018-06-11"]
     text: 
          label: ["Flooding in the northeast", "driven by x…"]
          x_loc: 0.88 #this is in percentage space, relative to the plotting device
          y_loc: 0.65
          pos: 3
     overlay_plot: 
          file: "1_fetch/in/custom_border_20180601_NE_flood.png"
   -      
     dates: ["2018-05-21", "2018-07-01"]
     text: 
          label: ["Drought conditions", "established in Colorado"]
          x_loc: 0.47
          y_loc: 0.45
          pos: 3
     text_box: 
          bg: "#A9A9A9CC"
```
